### PR TITLE
Add memtest86+ option to loader menu

### PR DESCRIPTION
**Pull request by jeamland**

### CODE REVIEW

**Review by amotin — APPROVED** [review]
I have no objections, if this works.

I always thought we could benefit from shipping memory test, but don't remember what stopped us.  Just curios why now?  I don't see ticket with some backgroud referenced in the commit messages, that would be good.

**Comment by kithrup** [comment]
We were using grub rather than the BSD loader before.  Now that we're using that, it's as reasonable a time as any to make this change.

**Review by kmoore134 — APPROVED** [review]
LGTM

**Comment by jeamland** [comment]
rebuild

**Pull request merged**
