### PR TITLE
Make the vncserver stop waiting when vm is destroyed

### PR DESCRIPTION
**Pull request by ghost**
Fixes the issue NAS-105890 was a workaround for.

### CODE REVIEW

**Comment by amotin** [comment]
This looks like very specific workaround.  And it handles only VNC case, not RFB.  It is probably better then nothing, but makes me wonder whether better solution is possible, or how it works on 11.3 (if Waqar is correct).

**Comment by ghost** [comment]
I can make the same change in rfb_init(). I didn't notice it does the same waiting. I'm not sure it's worth going too far with the refactoring here though, my understanding is we don't intend to upstream the vncserver part since it depends on several libraries from ports.

**Review by amotin — APPROVED** [review]
On a tactical level I am fine about this patch, I would just reduce timeout to 1 second instead of 3.  But on strategic level I would recommend to discuss it with other bhyve developers. And I think wait for VNS/RFB could be generalized, so that wait would happen not on stage of framebuffer device initialization, but somewhere in global code after all initialization is done and VM is ready to start.

**Comment by ghost** [comment]
I created [NAS-105896](https://jira.ixsystems.com/browse/NAS-105896) for generalizing and upstreaming this. I have an idea I will work on when I come back to it. This PR will work for now so I'll move on to other priorities at the moment.

**Pull request merged**
