### PR TITLE
Master update 20180209

### PR DESCRIPTION
**Pull request by kmoore134**
Update to latest HEAD in freenas/master

PROFILE: fn_head

### CODE REVIEW

**Comment by kmoore134** [comment]
rebuild

**Comment by kmoore134** [comment]
rebuild

**Comment by kmoore134** [comment]
rebuild

**Comment by kmoore134** [comment]
rebuild

**Comment by kmoore134** [comment]
rebuild

**Comment by kmoore134** [comment]
rebuild

**Comment by kmoore134** [comment]
rebuild

**Comment by kmoore134** [comment]
rebuild

**Comment by kmoore134** [comment]
rebuild

**Comment by amotin** [comment]
I did another pull couple days ago.

**Pull request closed without merging**
