### PR TITLE
Freebsd 11 update 20171129

### PR DESCRIPTION
**Pull request by kmoore134**
Ticket: #26917

### CODE REVIEW

**Comment by amotin** [comment]
Do we really wanna hurry with this before 11.1 release?  FreeBSD does not recommend significant code changes in alike time window between branching and release to not confuse users and simplify testing and bug fixing during the release process.

**Comment by kmoore134** [comment]
No, this is a merge into freenas/11-stable, not 11.1, but for 11.2 target. Just getting it done early ;)

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by amotin** [comment]
I understand it is to 11-stable.  But now as result of the merge 11-Nightly train will be very different from unreleased 11.1.  I would hold this till release.

**Review by amotin — APPROVED** [review]
This seem builds, and now it is better time to merge it.  We could also merge new diff for the last two weeks also.

**Comment by kmoore134** [comment]
I'll update this PR real quick before merge

**Comment by kmoore134** [comment]
Oh, thats right I already did that :) Merging!

**Comment by amotin** [comment]
It seems that you merged this as one commit.  Not exactly good for history tracking purposes.

**Comment by amotin** [comment]
And even worse is that that is makes impossible to cherry-pick individual commits out of if it into 11.1 branch.  Please don't do that again when individual commits matter.

**Comment by kmoore134** [comment]
That was not my intent, seems it saved my "Squash and merge" preference from previous commits. We can revert and re-merge with history if you like?

**Comment by amotin** [comment]
We probably can't have history rewritten without making everybody suffer.  What's about reverting and applying -- it would give some benefits for merging, but I don't have much experience with that and rebasing, if we do that later, to recommend.

**Comment by kmoore134** [comment]
https://github.com/freenas/os/pull/59 - There we go, created a revert PR, then I'll open a new one and push properly this time. Sorry about the mess!

**Pull request merged**
