### PR TITLE
Be far more strict about nfsd virtual host names

### PR DESCRIPTION
**Pull request by jhixson74**

### CODE REVIEW

**Comment by jhixson74** [comment]
Jenkins: retest this please

**Comment by jhixson74** [comment]
Jenkins: retest this please

**Comment by jhixson74** [comment]
Jenkins: retest this please

**Comment by jhixson74** [comment]
Jenkins: I give up

**Comment by kmoore134** [comment]
I checked and this is a failure on jenkins part. I need to add some logic so it understands that its using the fn_head profile for freenas/master branch.

**Pull request merged**
